before_script:
  - apt-get update -qq > /dev/null && apt-get install -y luarocks love > /dev/null
  - luarocks install luacheck
  - luarocks install lunatest

luacheck:
  script:
    - make check test fuzz
